server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: rest
          uri: http://localhost:8087
          predicates:
            - Path=/rest/**
            
      
        - id: Readapplication
          uri: http://localhost:9093 
          predicates:
            - Path=/Readapplication/**
            
            
        - id: update
          uri: http://localhost:8083
          predicates:
            - Path=/update/**
            
            
            
        - id: deletemethod
          uri: http://localhost:8081
          predicates:
            - Path=/deletemethod/** 
            
       
           
          
          
        
         
spring.:
  main:
    allow-bean-definition-overriding: true


#eureka:
  ## prefer-ip-address: true
 # client:
   # fetch-registry: true
    #register-with-eureka: true
    #service-url:
      #defaultZone: http://localhost:8761/eureka


#okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-06594147.okta.com/oauth2/default
    audience: api://default
    client-id: 0oadhxtcjkdhs4ICB5d7
    client-secret: sT4JtVh1T06R6UdbcJmTH4ndPjSQAz-yY-1LfzCtLtEFDR8L0yOxP4FYZ9LhiQ1K
    scopes: openid, profile, email, offline_access